title = "[a:web]: Der einzige Podcast 체bers Web, den du brauchst"
email = "awebpodcast@mozilla.com"
buildFuture = true
[params]
    description = "In dem unabh채ngigen Podcast [a:web] nehmen die Moderatorinnen Anja und Alice euch mit auf eine spannende Entdeckungsreise durch das Internet. Verst채ndlich f체r alle und nie langweilig. [a:web] ist ein Podcast von Firefox, dem Browser der auf deiner Seite ist. Firefox fights for you!"
